spring:
  application:
    name: batch-processing-demo

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

batch:
  sql:
    input: ${BATCH_SQL_INPUT:classpath:/local-input.sql}

server:
  port: 9001
