spring:
  application:
    name: batch-processing-demo

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      name: job2

server:
  port: 9001