apiVersion: v1
kind: Secret
metadata:
  name: batch-db-secret
  namespace: default
type: Opaque
# Los valores deben estar en base64: echo -n "valor" | base64
stringData:
  url:      "jdbc:postgresql://db-service:5432/batch_db"
  username: "batch_user"
  password: "CAMBIA_ESTO"
